---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age19sc3djjdnuxd5dqacgj8xkhews6v48ekjkt4xhydhvjzttv9euys7c7xgq"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age19sc3djjdnuxd5dqacgj8xkhews6v48ekjkt4xhydhvjzttv9euys7c7xgq"
